name: Deploy docs page

on: 
  push:
    branches:
      - docs

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/checkout@v4
    - name: Chmod
      run: cd app && chmod +x gradlew
    - name: Remove previous
      run: rm -r ./docs/*
    - name: Build wasmJsBrowserDistribution
      run: cd app && ./gradlew :docsApp:wasmJsBrowserDistribution
    - name: Move files
      run: cd app && mv docsApp/build/dist/wasmJs/productionExecutable/* ../docs/
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
    - name: Deploy artifact
      id: deployment
      uses: actions/deploy-pages@v4
